spring.application.name=paf
spring.data.mongodb.uri=mongodb://localhost:27017/smart_campus_db
server.port=8080
wrapperVersion=3.3.2
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip